import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: Platform.OS === "ios" ? 40 : 20,
    backgroundColor: "#f9f9f9",
  },
  header: {
    paddingHorizontal: 20,
    height: 100,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFCC00",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  logo: {
    width: 80,
    height: 70,
    marginTop: 30,
    resizeMode: "contain",
  },
  title: {
    fontSize: 28,
    marginTop: 30,
    fontWeight: "bold",
    marginLeft: 20,
  },
  cartContent: {
    paddingBottom: 140,
    alignItems: "center",
  },
  carrinho: {
    width: 90,
    height: 90,
    alignSelf: "center",
    marginTop: 50,
  },
  cartText: {
    fontSize: 18,
    color: "#262626",
    marginTop: 10,
    textAlign: "center",
  },
  marketCard: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    height: 130,
    width: 220,
    marginRight: 12,
  },
  marketName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  marketAddress: {
    fontSize: 14,
    color: "#666",
    marginVertical: 2,
  },
  marketPrice: {
    fontSize: 16,
    color: "#000",
    marginTop: 4,
  },
  qtyButton: {
    backgroundColor: "#FFCC00",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
    marginHorizontal: 10,
  },
  qtyButtonText: {
    fontSize: 18,
    fontWeight: "bold",
  },
  qtyText: {
    fontSize: 16,
    fontWeight: "600",
  },
  totalPursh: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "#fff",
    paddingVertical: 16,
    borderTopWidth: 1,
    borderColor: "#ddd",
    alignItems: "center",
    justifyContent: "center",
  },
  totalText: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    color: "#333",
  },
  checkoutButton: {
    backgroundColor: "#FF9900",
    paddingVertical: 12,
    borderRadius: 10,
    marginTop: 10,
    width: "80%",
    alignItems: "center",
  },
  checkoutText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
});
